/*  Course: CSC 236 Introduction to Programming with C++
    Name: Abdirahman Mohamed
    Assignment A06: Hello world
    Description: This default C++ program types "Hello world!" on the screen
    All of the code in this program was generated by Code::Blocks */

#include <iostream>

using namespace std;

int main()
{
    cout << "Hello world!" << endl;
    return 0;
}
